
#另外一种写法：对microservice-provider-one服务的反向代理
#url使用/provider-one/**替代，例如:http://localhost:8099/provider-one/handle
zuul:
  routes:
    abc:  #这里随便写
      path: /provider-one/**
      serviceId: microservice-provider-one
